changelog:
  categories:
    - title: Breaking changes
      labels: [breaking-change]
    - title: New features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Documentation and maintenance
      labels: [documentation, dependencies, chore]
    - title: Other changes
      labels: ["*"]
